{% set name = "mt940" %}
{% set version = "4.29.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/mt-940/mt-940-{{ version }}.tar.gz
  sha256: f7795740b8fd2ce7d963163867bb76ebd1b593f6798fcc9e5f319a05b9a2dd78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=39.1.0
  run:
    - python >=3.6

test:
  imports:
    - mt940
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WoLpH/mt940
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library to parse MT940 files and returns smart Python collections for statistics and manipulation.
  description: |
    A library to parse MT940 files and returns smart Python collections
    for statistics and manipulation.
  doc_url: https://mt940.readthedocs.io
  dev_url: https://github.com/WoLpH/mt940

extra:
  recipe-maintainers:
    - jan-janssen
