{% set name = "mt940" %}
{% set version = "4.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/mt-940/mt-940-{{ version }}.tar.gz
  sha256: da14e2ec84d6c6e85604d2a6b8a800b08ec6000351acde501c41eb662819295c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=39.1.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - mt940
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WoLpH/mt940
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library to parse MT940 files and returns smart Python collections for statistics and manipulation.
  description: |
    A library to parse MT940 files and returns smart Python collections
    for statistics and manipulation.
  doc_url: https://mt940.readthedocs.io
  dev_url: https://github.com/WoLpH/mt940

extra:
  recipe-maintainers:
    - jan-janssen
